name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt-openj9'
          java-version: '11'
      - run: ./gradlew ktlintCheck
      - run: ./gradlew build
